package org.altar.session4.test;

public enum EpicEnum {
	//FROM 0 to ...
	LORD_OF_THE_RINGS,
	DUNE,
	BATTLESTAR_GALACTICA,
	STAR_TREK,
	STAR_WARS,
	FOUNDATION,
	GAME_OF_THRONES,
	WARCRAFT,
	DIABLO,
	PATRULHA_PATA;
}